### ISSUE TITLE
File doesn't exists in the repository

### ISSUE THREAD

**Issue by nanounanue** [dssg/model_monitor#1]
https://github.com/dssg/model_monitor/blob/63fbeb77f4464bbf74b3b2443a223fcd82fecd31/src/model_monitor/schemas/schema.py#L16

**Comment by jeremys93** [comment]
https://github.com/dssg/model_monitor/commit/2a0d45954dec9e014fa38ca6bdabde49b27692c9#diff-2680f1d184b390b2077e0217aaadcd19L16

Line removed, from outdated version
