### ISSUE TITLE
Are the primary keys SERIAL (i.e. autogenerated)?

### ISSUE THREAD

**Issue by nanounanue** [dssg/model_monitor#7]
If so you should be explicit on it and add the argument `autoincrement=True`

https://github.com/dssg/model_monitor/blob/63fbeb77f4464bbf74b3b2443a223fcd82fecd31/src/model_monitor/schemas/schema.py#L30

**Comment by nanounanue** [comment]
Are you targeting PostgreSQL 10? If so, `SERIAL` has been superseded (see sqlalchemy 1.2 docs)

**Comment by jeremys93** [comment]
I don't have a strong preference, would you prefer to target postgres 9 or 10?

**Comment by jeremys93** [comment]
added, targeting postgres9 as discussed earlier
